Optimize compression with pigz and add more error checks

diff --git a/src/backup b/src/backup
--- a/src/backup
+++ b/src/backup
@@ -3,23 +3,26 @@ set -e
 set -o pipefail
 
 cleanup() {
-  echo "Cleanup backup older than $CLEANUP_OLDER_THAN days"
-  toberemove=$(find /backups/ -type f -not -name ".*" -mtime +$CLEANUP_OLDER_THAN | wc -l)
-  echo "Will try to remove $toberemove files"
-  find /backups/ -type f -not -name ".*" -mtime +$CLEANUP_OLDER_THAN -exec rm {} \;
+    echo "Cleaning up backups older than $CLEANUP_OLDER_THAN days"
+    to_be_removed=$(find /backups/ -type f -not -name ".*" -mtime +$CLEANUP_OLDER_THAN | wc -l)
+    echo "Removing $to_be_removed files"
+    find /backups/ -type f -not -name ".*" -mtime +$CLEANUP_OLDER_THAN -exec rm {} \;
 }
 
-if [ -z "$MYSQL_ENV_MYSQL_HOST" ]; then echo "Error: MYSQL_ENV_MYSQL_HOST not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "$MYSQL_ENV_MYSQL_USER" ]; then echo "Error: MYSQL_ENV_MYSQL_USER not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "$MYSQL_ENV_MYSQL_DATABASE" ]; then echo "Error: MYSQL_ENV_MYSQL_DATABASE not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "$MYSQL_ENV_MYSQL_PASSWORD" ]; then echo "Error: MYSQL_ENV_MYSQL_PASSWORD not set"; echo "Finished: FAILURE"; exit 1; fi
+for var in MYSQL_ENV_MYSQL_HOST MYSQL_ENV_MYSQL_USER MYSQL_ENV_MYSQL_DATABASE MYSQL_ENV_MYSQL_PASSWORD; do
+    if [ -z "$(eval echo \$$var)" ]; then
+        echo "Error: $var not set"
+        echo "Finished: FAILURE"
+        exit 1
+    fi
+done
 
-if [ -n "$CLEANUP_OLDER_THAN" ]; then cleanup;  fi
+if [ -n "$CLEANUP_OLDER_THAN" ]; then cleanup; fi
 
-echo 'creating backup archive of /var/www/html'
-tar --create --gzip -vv --directory="/var/www/html/" --file="/backups/backup_`date '+%Y%m%d'`.tar.gz" "./"
+echo 'Creating backup archive of /var/www/html'
+tar --create --directory="/var/www/html/" ./ | pigz -p 4 > "/backups/backup_$(date '+%Y%m%d').tar.gz"
 
-echo 'creating database dump'
-mysqldump --host="${MYSQL_ENV_MYSQL_HOST}" --add-drop-table --no-tablespaces --user="${MYSQL_ENV_MYSQL_USER}" --password="${MYSQL_ENV_MYSQL_PASSWORD}" "${MYSQL_ENV_MYSQL_DATABASE}" --single-transaction --column-statistics=0 | bzip2 -c > "/backups/backup_`date '+%Y%m%d'`.sql.bz2"
+echo 'Creating database dump'
+mysqldump --host="$MYSQL_ENV_MYSQL_HOST" --user="$MYSQL_ENV_MYSQL_USER" --password="$MYSQL_ENV_MYSQL_PASSWORD" --add-drop-table --no-tablespaces --single-transaction "$MYSQL_ENV_MYSQL_DATABASE" | bzip2 > "/backups/backup_$(date '+%Y%m%d').sql.bz2"
 
 echo 'Finished: SUCCESS'
diff --git a/src/restore b/src/restore
--- a/src/restore
+++ b/src/restore
@@ -1,64 +1,58 @@
 #!/bin/sh
 set -e
 
-if ! [[ "$1" ]]
-then
+if [ -z "$1" ]; then
     echo "Error: Backup name missing"
-    echo "Please specify a backup name, e.g. 'restore 20141104'"
+    echo "Please specify a backup name, e.g., 'restore 20141104'"
     echo "Finished: FAILURE"
     exit 1
 fi
 
-if [ -z "$MYSQL_ENV_MYSQL_HOST" ]; then echo "Error: MYSQL_ENV_MYSQL_HOST not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "$MYSQL_ENV_MYSQL_USER" ]; then echo "Error: MYSQL_ENV_MYSQL_USER not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "$MYSQL_ENV_MYSQL_DATABASE" ]; then echo "Error: MYSQL_ENV_MYSQL_DATABASE not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "$MYSQL_ENV_MYSQL_PASSWORD" ]; then echo "Error: MYSQL_ENV_MYSQL_PASSWORD not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "$MYSQL_PORT_3306_TCP_PORT" ]; then echo "Error: MYSQL_PORT_3306_TCP_PORT not set"; echo "Finished: FAILURE"; exit 1; fi
+for var in MYSQL_ENV_MYSQL_HOST MYSQL_ENV_MYSQL_USER MYSQL_ENV_MYSQL_DATABASE MYSQL_ENV_MYSQL_PASSWORD; do
+    if [ -z "$(eval echo \$$var)" ]; then
+        echo "Error: $var not set"
+        echo "Finished: FAILURE"
+        exit 1
+    fi
+done
 
-if ! [[ $1 =~ ^[a-zA-Z0-9_-]+$ ]]
-then
-  echo "The given backup name does not match the expected pattern: only characters, digits, underscore and dash are allowed ([a-zA-Z0-9_-])."
-  echo 'Finished: FAILURE'
-  exit 1
+if ! echo "$1" | grep -Eq '^[a-zA-Z0-9_-]+$'; then
+    echo "The given backup name does not match the expected pattern: only characters, digits, underscore, and dash are allowed ([a-zA-Z0-9_-])."
+    echo "Finished: FAILURE"
+    exit 1
 fi
 
 FILES_ARCHIVE="/backups/backup_$1.tar.gz"
 SQL_ARCHIVE="/backups/backup_$1.sql.bz2"
 
-if [[ ! -f "${FILES_ARCHIVE}" ]]
-then
-  echo "The file $FILES_ARCHIVE does not exist. Aborting."
-  echo "Finished: FAILURE."
-  exit 1
+if [ ! -f "${FILES_ARCHIVE}" ]; then
+    echo "The file $FILES_ARCHIVE does not exist. Aborting."
+    echo "Finished: FAILURE."
+    exit 1
 fi
 
-if [[ ! -f "${SQL_ARCHIVE}" ]]
-then
-  echo "The file $SQL_ARCHIVE does not exist. Aborting."
-  echo "Finished: FAILURE."
-  exit 1
+if [ ! -f "${SQL_ARCHIVE}" ]; then
+    echo "The file $SQL_ARCHIVE does not exist. Aborting."
+    echo "Finished: FAILURE."
+    exit 1
 fi
 
+echo "Deleting files from /var/www/html/"
+rm -rf /var/www/html/*
 
-# cleanup html folder
-echo "deleting files from /var/www/html/"
-rm -R /var/www/html/*
+echo "Restoring files from $FILES_ARCHIVE to /var/www/html"
+pigz -dc "${FILES_ARCHIVE}" | tar -xzf - --directory="/var/www/html/"
 
-# restore files
-echo "restoring files from $FILES_ARCHIVE to /var/www/html"
-tar -xzf "${FILES_ARCHIVE}" --directory="/var/www/html/"
+WP_CONFIG="/var/www/html/wp-config.php"
+sed -i -e "s/define('DB_NAME', '.*');/define('DB_NAME', '$MYSQL_ENV_MYSQL_DATABASE');/" \
+       -e "s/define('DB_USER', '.*');/define('DB_USER', '$MYSQL_ENV_MYSQL_USER');/" \
+       -e "s/define('DB_PASSWORD', '.*');/define('DB_PASSWORD', '$MYSQL_ENV_MYSQL_PASSWORD');/" \
+       -e "s/define('DB_HOST', '.*');/define('DB_HOST', '$MYSQL_ENV_MYSQL_HOST:$MYSQL_PORT_3306_TCP_PORT');/" \
+       "$WP_CONFIG"
 
-# update wp-config.php
-sed -i s/"define('DB_NAME', '.*');"/"define('DB_NAME', '$MYSQL_ENV_MYSQL_DATABASE');"/g /var/www/html/wp-config.php
-sed -i s/"define('DB_USER', '.*');"/"define('DB_USER', '$MYSQL_ENV_MYSQL_USER');"/g /var/www/html/wp-config.php
-sed -i s/"define('DB_PASSWORD', '.*');"/"define('DB_PASSWORD', '$MYSQL_ENV_MYSQL_PASSWORD');"/g /var/www/html/wp-config.php
-sed -i s/"define('DB_HOST', '.*');"/"define('DB_HOST', '$MYSQL_ENV_MYSQL_HOST:$MYSQL_PORT_3306_TCP_PORT');"/g /var/www/html/wp-config.php
-
-# set correct file owner
 chown -R www-data:www-data /var/www/html
 
-# restore database
-echo "restoring data from mysql dump file $SQL_ARCHIVE"
-bunzip2 < "${SQL_ARCHIVE}" | mysql --user="${MYSQL_ENV_MYSQL_USER}" --password="${MYSQL_ENV_MYSQL_PASSWORD}" --host="${MYSQL_ENV_MYSQL_HOST}" "${MYSQL_ENV_MYSQL_DATABASE}"
+echo "Restoring data from MySQL dump file $SQL_ARCHIVE"
+bunzip2 < "${SQL_ARCHIVE}" | mysql --host="$MYSQL_ENV_MYSQL_HOST" --user="$MYSQL_ENV_MYSQL_USER" --password="$MYSQL_ENV_MYSQL_PASSWORD" "$MYSQL_ENV_MYSQL_DATABASE"
 
 echo 'Finished: SUCCESS'
